// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type UserInfoReq struct {
	UserID int64 `json:"user_id"`
}

type UserInfoResp struct {
	UserID   int64  `json:"user_id"`
	Nickname string `json:"nickname"`
}
