// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"Task5/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authenticate},
			[]rest.Route{
				{
					// 创建评论
					Method:  http.MethodPost,
					Path:    "/createComment",
					Handler: CreateCommentHandler(serverCtx),
				},
				{
					// 创建文章
					Method:  http.MethodPost,
					Path:    "/createPost",
					Handler: CreatePostHandler(serverCtx),
				},
				{
					// 删除文章
					Method:  http.MethodPost,
					Path:    "/deletePost",
					Handler: DeletePostHandler(serverCtx),
				},
				{
					// 获取用户名
					Method:  http.MethodPost,
					Path:    "/getUserName",
					Handler: GetUserNameHandler(serverCtx),
				},
				{
					// 查询所有评论
					Method:  http.MethodPost,
					Path:    "/queryAllComment",
					Handler: QueryAllCommentHandler(serverCtx),
				},
				{
					// 查询所有文章
					Method:  http.MethodPost,
					Path:    "/queryAllPost",
					Handler: QueryAllPostHandler(serverCtx),
				},
				{
					// 查询文章
					Method:  http.MethodPost,
					Path:    "/queryPost",
					Handler: QueryPostHandler(serverCtx),
				},
				{
					// 更新文章
					Method:  http.MethodPost,
					Path:    "/updatePost",
					Handler: UpdatePostHandler(serverCtx),
				},
			}...,
		),
	)
}
