// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommonResp struct {
	Message string `json:"Message"`
}

type CreateCommentReq struct {
	PostId  uint64 `json:"post_id"`
	Content string `json:"content"`
}

type CreatePostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type DeletePostReq struct {
	Id uint64 `json:"id"`
}

type GetUserNameReq struct {
}

type GetUserNameResp struct {
	UserName string `json:"UserName"`
}

type LoginReq struct {
	UserName string `json:"UserName"`
	Password string `json:"Password"`
}

type LoginResp struct {
	ExpiresAt int64  `json:"ExpiresAt"`
	Token     string `json:"Token"`
	User      UserInfo
}

type QueryCommentResp struct {
	PostId uint64 `json:"post_id"`
}

type QueryPostReq struct {
	Id uint64 `json:"id"`
}

type QueryPostResp struct {
	Id      uint64 `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type RegisterReq struct {
	UserName string `json:"UserName"`
	Password string `json:"Password"`
}

type RegisterResp struct {
	Message string `json:"Message"`
}

type UpdatePostReq struct {
	Id      uint64 `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UserInfo struct {
	ID       uint64 `json:"ID"`
	UserName string `json:"UserName"`
}
